// GENERATED by deploy/tools/probe_cpp/gen_joint_map.py -- do not edit.
//
// Slot numbers come from the R1JointIndex enum in unitree_sdk2's
// example/r1 mapped through its motor-index array, cross-checked against
// probe_lowstate --map measurements on the robot. Do NOT #include the
// vendor enum directly: it has RightShoulderPitch = 29, a typo for 19,
// which as a slot number addresses head_pitch.
//
// See deploy/interface/joint_map_r1.md for the evidence per row.
#pragma once

#include <array>
#include <cstddef>

namespace r1_hw_bridge
{

inline constexpr std::size_t kNumJoints = 26;
inline constexpr std::size_t kNumSlots = 35;

// Indexed by our articulation order; value is the unitree_hg motor slot.
inline constexpr std::array<int, kNumJoints> kJointSlot = {
   0,  //  0 left_hip_pitch_joint (measured)
   6,  //  1 right_hip_pitch_joint (measured)
  12,  //  2 waist_roll_joint (enum)
   1,  //  3 left_hip_roll_joint (enum)
   7,  //  4 right_hip_roll_joint (enum)
  13,  //  5 waist_yaw_joint (enum)
   2,  //  6 left_hip_yaw_joint (enum)
   8,  //  7 right_hip_yaw_joint (enum)
  29,  //  8 head_pitch_joint (measured)
  15,  //  9 left_shoulder_pitch_joint (enum)
  22,  // 10 right_shoulder_pitch_joint (enum)
   3,  // 11 left_knee_joint (measured)
   9,  // 12 right_knee_joint (enum)
  30,  // 13 head_yaw_joint (enum)
  16,  // 14 left_shoulder_roll_joint (measured)
  23,  // 15 right_shoulder_roll_joint (enum)
   4,  // 16 left_ankle_pitch_joint (enum)
  10,  // 17 right_ankle_pitch_joint (enum)
  17,  // 18 left_shoulder_yaw_joint (enum)
  24,  // 19 right_shoulder_yaw_joint (enum)
   5,  // 20 left_ankle_roll_joint (measured)
  11,  // 21 right_ankle_roll_joint (enum)
  18,  // 22 left_elbow_joint (enum)
  25,  // 23 right_elbow_joint (enum)
  19,  // 24 left_wrist_roll_joint (enum)
  26,  // 25 right_wrist_roll_joint (enum)
};

// Articulation default pose (rad). joint_pos obs = measured - this.
inline constexpr std::array<float, kNumJoints> kDefaultPos = {
  -0.100000f,  //  0 left_hip_pitch_joint
  -0.100000f,  //  1 right_hip_pitch_joint
  +0.000000f,  //  2 waist_roll_joint
  +0.000000f,  //  3 left_hip_roll_joint
  +0.000000f,  //  4 right_hip_roll_joint
  +0.000000f,  //  5 waist_yaw_joint
  +0.000000f,  //  6 left_hip_yaw_joint
  +0.000000f,  //  7 right_hip_yaw_joint
  +0.000000f,  //  8 head_pitch_joint
  +0.350000f,  //  9 left_shoulder_pitch_joint
  +0.350000f,  // 10 right_shoulder_pitch_joint
  +0.300000f,  // 11 left_knee_joint
  +0.300000f,  // 12 right_knee_joint
  +0.000000f,  // 13 head_yaw_joint
  +0.180000f,  // 14 left_shoulder_roll_joint
  -0.180000f,  // 15 right_shoulder_roll_joint
  -0.200000f,  // 16 left_ankle_pitch_joint
  -0.200000f,  // 17 right_ankle_pitch_joint
  +0.000000f,  // 18 left_shoulder_yaw_joint
  +0.000000f,  // 19 right_shoulder_yaw_joint
  +0.000000f,  // 20 left_ankle_roll_joint
  +0.000000f,  // 21 right_ankle_roll_joint
  +0.870000f,  // 22 left_elbow_joint
  +0.870000f,  // 23 right_elbow_joint
  +0.000000f,  // 24 left_wrist_roll_joint
  +0.000000f,  // 25 right_wrist_roll_joint
};

inline constexpr std::size_t kNumActions = 24;
// Action index -> articulation index. NOT the identity.
inline constexpr std::array<int, kNumActions> kActionToArt = {
   0,  // action  0 -> left_hip_pitch_joint
   1,  // action  1 -> right_hip_pitch_joint
   2,  // action  2 -> waist_roll_joint
   3,  // action  3 -> left_hip_roll_joint
   4,  // action  4 -> right_hip_roll_joint
   5,  // action  5 -> waist_yaw_joint
   6,  // action  6 -> left_hip_yaw_joint
   7,  // action  7 -> right_hip_yaw_joint
   9,  // action  8 -> left_shoulder_pitch_joint
  10,  // action  9 -> right_shoulder_pitch_joint
  11,  // action 10 -> left_knee_joint
  12,  // action 11 -> right_knee_joint
  14,  // action 12 -> left_shoulder_roll_joint
  15,  // action 13 -> right_shoulder_roll_joint
  16,  // action 14 -> left_ankle_pitch_joint
  17,  // action 15 -> right_ankle_pitch_joint
  18,  // action 16 -> left_shoulder_yaw_joint
  19,  // action 17 -> right_shoulder_yaw_joint
  20,  // action 18 -> left_ankle_roll_joint
  21,  // action 19 -> right_ankle_roll_joint
  22,  // action 20 -> left_elbow_joint
  23,  // action 21 -> right_elbow_joint
  24,  // action 22 -> left_wrist_roll_joint
  25,  // action 23 -> right_wrist_roll_joint
};

}  // namespace r1_hw_bridge
