#!/usr/bin/env python3
"""Build the R1 slot map: our 26 articulation joints -> unitree_hg motor slots.

Three independent sources, deliberately kept separate so a disagreement is
visible rather than averaged away:

  1. joints.tsv            our joint order + action indices, generated from
                           policy_interface.json (gen_joints.py).
  2. R1JointIndex + array  from unitree_sdk2/example/r1/low_level/
                           r1_ankle_swing_example.cpp. The enum values index
                           the motor-index array; they are NOT slot numbers.
  3. joint_map*.tsv        rows measured on the robot with `probe_lowstate --map`.

Source 2 alone is not evidence: the same file has `RightShoulderPitch = 29`,
which is a typo for 19 and, used as a slot number, would send the right
shoulder's command to the head. Source 3 is what makes a row trustworthy.
"""
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent

# enum R1JointIndex, in value order. Values are indices into MOTOR_SLOT below.
ENUM = ["LeftHipPitch", "LeftHipRoll", "LeftHipYaw", "LeftKnee",
        "LeftAnklePitch", "LeftAnkleRoll",
        "RightHipPitch", "RightHipRoll", "RightHipYaw", "RightKnee",
        "RightAnklePitch", "RightAnkleRoll",
        "WaistRoll", "WaistYaw",
        "LeftShoulderPitch", "LeftShoulderRoll", "LeftShoulderYaw",
        "LeftElbow", "LeftWristRoll",
        "RightShoulderPitch", "RightShoulderRoll", "RightShoulderYaw",
        "RightElbow", "RightWristRoll",
        "HEAD_PITCH", "HEAD_YAW"]

# The motor-index array. Tail read directly from the example; the leading 0..13
# is forced by the measured array[5]=5 and array[6]=6 together with the survey's
# dead slots (14, 20-21, 27-28, 31-34).
MOTOR_SLOT = list(range(14)) + [15, 16, 17, 18, 19, 22, 23, 24, 25, 26, 29, 30]

assert len(ENUM) == len(MOTOR_SLOT) == 26


def to_urdf(name: str) -> str:
    if name.startswith("HEAD_"):
        return f"head_{name[5:].lower()}_joint"
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower() + "_joint"


def load_joints():
    rows = []
    for line in (HERE / "joints.tsv").read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        art, name, act = line.split("\t")
        rows.append((int(art), name, int(act)))
    return rows


def load_defaults():
    """Articulation default pose. The policy's joint_pos observation is relative
    to this, so the bridge needs all 26 -- policy_interface.yaml only carries the
    24 actuated ones."""
    import json
    spec = json.loads((HERE.parents[1] / "interface" /
                       "policy_interface.json").read_text())
    return spec["articulation"]["default_joint_pos"]


def load_measured(paths):
    """Later files win, so a re-test supersedes the run it corrects."""
    out = {}
    for p in paths:
        if not pathlib.Path(p).exists():
            continue
        for line in pathlib.Path(p).read_text().splitlines():
            if not line or line.startswith(("#", "slot")):
                continue
            f = line.split("\t")
            out[f[2]] = (int(f[0]), float(f[4]), f[6] if len(f) > 6 else "")
    return out


def emit_header(joints, predicted, measured, out):
    """C++ header for the bridge. Generated, never hand-written: a transcription
    error here puts torque on the wrong joint and nothing reports it."""
    lines = [
        "// GENERATED by deploy/tools/probe_cpp/gen_joint_map.py -- do not edit.",
        "//",
        "// Slot numbers come from the R1JointIndex enum in unitree_sdk2's",
        "// example/r1 mapped through its motor-index array, cross-checked against",
        "// probe_lowstate --map measurements on the robot. Do NOT #include the",
        "// vendor enum directly: it has RightShoulderPitch = 29, a typo for 19,",
        "// which as a slot number addresses head_pitch.",
        "//",
        "// See deploy/interface/joint_map_r1.md for the evidence per row.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "",
        "namespace r1_hw_bridge",
        "{",
        "",
        f"inline constexpr std::size_t kNumJoints = {len(joints)};",
        f"inline constexpr std::size_t kNumSlots = 35;",
        "",
        "// Indexed by our articulation order; value is the unitree_hg motor slot.",
        f"inline constexpr std::array<int, kNumJoints> kJointSlot = {{",
    ]
    for art, name, act in joints:
        ev = "measured" if measured.get(name, (None,))[0] == predicted[name] else "enum"
        lines.append(f"  {predicted[name]:>2},  // {art:>2} {name} ({ev})")
    lines += ["};", ""]

    # joint_pos is reported relative to the default pose, so the bridge cannot
    # build an observation without all 26 defaults.
    lines += ["// Articulation default pose (rad). joint_pos obs = measured - this.",
              f"inline constexpr std::array<float, kNumJoints> kDefaultPos = {{"]
    for (art, name, _), d in zip(joints, load_defaults()):
        lines.append(f"  {d:+.6f}f,  // {art:>2} {name}")
    lines += ["};", ""]

    # The policy emits 24 actions; they address 24 of the 26 articulation joints
    # (the head is not actuated). Index i in the action vector is a different
    # joint from index i in joint_pos -- the single most likely place to be off.
    act_to_art = [art for art, _, act in joints if act >= 0]
    act_to_art = [a for _, a in sorted(
        (act, art) for art, _, act in joints if act >= 0)]
    lines += [f"inline constexpr std::size_t kNumActions = {len(act_to_art)};",
              "// Action index -> articulation index. NOT the identity.",
              f"inline constexpr std::array<int, kNumActions> kActionToArt = {{"]
    names = {art: n for art, n, _ in joints}
    for act_i, art_i in enumerate(act_to_art):
        lines.append(f"  {art_i:>2},  // action {act_i:>2} -> {names[art_i]}")
    lines += ["};", "", "}  // namespace r1_hw_bridge", ""]
    pathlib.Path(out).write_text("\n".join(lines))


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("--")]
    header = next((a.split("=", 1)[1] for a in argv[1:]
                   if a.startswith("--header=")), None)
    joints = load_joints()
    measured = load_measured(args)
    predicted = {to_urdf(n): MOTOR_SLOT[i] for i, n in enumerate(ENUM)}

    print("| art | joint | action | slot | 证据 | 实测 Δ |")
    print("|---|---|---|---|---|---|")
    conflicts, verified = [], 0
    for art, name, act in joints:
        slot = predicted.get(name)
        if slot is None:
            conflicts.append(f"{name}: enum 里没有对应项")
            continue
        m = measured.get(name)
        if m is None:
            ev, delta = "仅 enum", "—"
        elif m[0] == slot:
            ev, delta, verified = "**实测确认**", f"{m[1]:+.3f}", verified + 1
        else:
            ev, delta = f"⚠️ **实测得 {m[0]}**", f"{m[1]:+.3f}"
            conflicts.append(f"{name}: enum 说 {slot}, 实测 {m[0]}")
        print(f"| {art} | `{name}` | {act if act >= 0 else '—'} | "
              f"**{slot}** | {ev} | {delta} |")

    used = sorted(predicted.values())
    print(f"\n槽位覆盖: {len(set(used))} 个互不重复, "
          f"范围 {min(used)}-{max(used)}")
    print(f"实测确认: {verified}/26")
    if conflicts:
        print("\n**冲突（必须解决后才能写 bridge）:**")
        for c in conflicts:
            print(f"- {c}")
        return 1
    if header:
        emit_header(joints, predicted, measured, header)
        print(f"\n生成头文件: {header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
