#!/usr/bin/env python3
"""Regenerate the two ROS configs from a staged policy bundle. Runs on the ROBOT.

`deploy/tools/dump_interface.py` produces r1_policy_runner's yaml by introspecting
the live Isaac Lab task, which needs the simulator and therefore cannot run on the
Orin. This script produces the same file from the bundle's policy_interface.json,
so the robot can regenerate its configs with nothing but python3.

It also rewrites the three cmd_vel envelope lines in bridge.yaml from the
bundle's command_envelope.json, in place, and refuses if they are not all there --
a policy swap that silently keeps the previous policy's envelope is how an
out-of-distribution command gets sent to a new policy on its first run.

    ./gen_configs.py <bundle_dir> --deploy $R1_DEPLOY_ROOT
    ./gen_configs.py <bundle_dir> --deploy $R1_DEPLOY_ROOT --check   # diff only
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

AXIS_PARAM = {"vx": "cmd_vel_x_range", "vy": "cmd_vel_y_range", "wz": "cmd_vel_yaw_range"}


def fmt_floats(values, places=6):
    return "[" + ", ".join("{:.{p}f}".format(float(v), p=places) for v in values) + "]"


def fmt_minimal(values):
    """Shortest exact-looking form: 0.0 stays 0.0, -0.5 stays -0.5.

    Used for the envelope so that re-installing an unchanged bundle is a genuine
    no-op on bridge.yaml. A generator that reformats every number it touches
    makes a real change indistinguishable from a cosmetic one in git.
    """
    out = []
    for v in values:
        f = float(v)
        s = repr(f)
        out.append(s if "." in s or "e" in s else s + ".0")
    return "[" + ", ".join(out) + "]"


def runner_yaml(spec: dict, run_id: str) -> str:
    obs, act = spec["observation"], spec["action"]
    # Name the joints the policy does NOT drive. On this robot that is the head,
    # and the fact that it is held at its default pose rather than commanded is
    # the kind of thing a reader of this file needs told, not left to infer.
    not_driven = [n for n in spec["articulation"]["joint_names"]
                  if n not in set(act["joint_names"])]
    absent = (" (not actuated: {})".format(", ".join(not_driven))
              if not_driven else "")
    names = ", ".join('"{}"'.format(t["name"]) for t in obs["terms"])
    widths = ", ".join(str(int(t["width"])) for t in obs["terms"])
    return (
        "# GENERATED by policy_pack/gen_configs.py from the installed bundle --\n"
        "# do not edit by hand. Re-running install_bundle.sh overwrites it.\n"
        "# source run: {run}\n"
        "#\n"
        "# Consumed by r1_policy_node. The node cross-checks obs_term_widths x\n"
        "# history_length against the engine's input dimension and refuses to start\n"
        "# if they disagree, so a stale copy of this file cannot silently mis-feed\n"
        "# the policy.\n"
        "/**:\n"
        "  ros__parameters:\n"
        "    control_rate_hz: {rate}\n"
        "    history_length: {hist}\n"
        "    obs_term_names: [{names}]\n"
        "    obs_term_widths: [{widths}]\n"
        "    # {nact} actuated joints, articulation order{absent}\n"
        "    action_scale: {scale}\n"
        "    default_joint_pos: {dpos}\n"
    ).format(run=run_id,
             rate=float(spec["control"]["control_rate_hz"]),
             hist=int(obs["history_length"]),
             names=names, widths=widths, nact=int(act["dim"]),
             absent=absent, scale=fmt_floats(act["scale"]),
             dpos=fmt_floats(act["default_pos"]))


def patch_bridge_yaml(text: str, env: dict):
    """Replace exactly the three envelope lines. Returns (new_text, changes)."""
    changes = []
    for axis, param in AXIS_PARAM.items():
        pattern = re.compile(r"^(\s*){}\s*:\s*\[[^\]]*\]\s*$".format(param), re.M)
        m = pattern.search(text)
        if not m:
            raise SystemExit(
                "[fail] bridge.yaml has no '{}' line to replace.\n"
                "       Refusing to append one: if the envelope is not already a\n"
                "       parameter there, this bridge predates the clamp and the\n"
                "       new policy would run with no envelope check at all."
                .format(param))
        new_line = "{}{}: {}".format(m.group(1), param, fmt_minimal(env[axis]))
        if m.group(0).strip() != new_line.strip():
            changes.append("{}: {} -> {}".format(param, m.group(0).strip(),
                                                 new_line.strip()))
        text = text[:m.start()] + new_line + text[m.end():]
    return text, changes


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("bundle")
    ap.add_argument("--deploy", required=True, help="the deploy/ tree to write into")
    ap.add_argument("--check", action="store_true",
                    help="report what would change, write nothing")
    args = ap.parse_args()

    bundle = pathlib.Path(args.bundle).expanduser().resolve()
    deploy = pathlib.Path(args.deploy).expanduser().resolve()
    spec = json.loads((bundle / "policy_interface.json").read_text())
    env = json.loads((bundle / "command_envelope.json").read_text())
    run_id = json.loads((bundle / "provenance.json").read_text())["run_id"]

    runner = deploy / "ros2_ws/src/r1_policy_runner/config/policy_interface.yaml"
    bridge = deploy / "ros2_ws/src/r1_hw_bridge/config/bridge.yaml"
    for p in (runner, bridge):
        if not p.is_file():
            raise SystemExit("[fail] not found: {}".format(p))

    want_runner = runner_yaml(spec, run_id)
    original = bridge.read_text()
    bridge_text, changes = patch_bridge_yaml(original, env)
    # bridge.yaml is hand-maintained apart from these three lines. A generator
    # that silently drops its trailing newline turns a three-line change into a
    # whole-file diff, so preserve it exactly.
    if original.endswith("\n") and not bridge_text.endswith("\n"):
        bridge_text += "\n"

    if args.check:
        have = runner.read_text()
        same = have == want_runner
        print("policy_interface.yaml: {}".format("unchanged" if same else "WOULD CHANGE"))
        if not same:
            # Show it. "WOULD CHANGE" on its own leaves the operator unable to
            # tell a comment rewrite from a changed observation contract.
            import difflib
            diff = list(difflib.unified_diff(
                have.splitlines(), want_runner.splitlines(),
                "installed", "from bundle", lineterm="", n=0))
            body = [d for d in diff[2:] if not d.startswith("@@")]
            if all(d.lstrip("+- ").startswith("#") for d in body):
                print("  (comment lines only -- the parameters are identical)")
            for d in diff:
                print("  " + d)
        print("bridge.yaml envelope : {}".format(
            "unchanged" if not changes else "WOULD CHANGE"))
        for c in changes:
            print("  " + c)
        return 0 if (same and not changes) else 1

    runner.write_text(want_runner)
    print("wrote {}".format(runner))
    bridge.write_text(bridge_text)
    if changes:
        print("patched {} envelope:".format(bridge.name))
        for c in changes:
            print("  " + c)
    else:
        print("{} envelope already matches the bundle".format(bridge.name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
